import { useEffect, useState } from 'react';
import { Store, Phone, Mail, MapPin, Clock, Star, ShoppingCart, Package, Save, Pencil } from 'lucide-react';

const api = '/seller-api/seller/shop?sellerCode=SL-BT-0001';
export default function ShopInfoPage() {
  const [shop, setShop] = useState<any>(null); const [editing,setEditing]=useState(false); const [saving,setSaving]=useState(false);
  useEffect(()=>{fetch(api).then(r=>r.json()).then(setShop);},[]);
  if(!shop) return <div className="p-6 text-gray-500">Đang tải thông tin shop...</div>;
  const change=(key:string,value:string)=>setShop((s:any)=>({...s,[key]:value}));
  const save=async()=>{setSaving(true);const r=await fetch(api,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(shop)});setShop(await r.json());setSaving(false);setEditing(false);};
  const fields=[['phone','Điện thoại',Phone],['email','Email',Mail],['address','Địa chỉ',MapPin],['openingHours','Giờ mở cửa',Clock]];
  const rating=Math.max(0,Math.min(5,Number(shop.rating||0)));
  return <div className="space-y-5 max-w-2xl mx-auto"><div className="flex justify-between items-center"><h1 className="text-2xl font-bold">Thông tin shop</h1>{editing?<button onClick={save} disabled={saving} className="flex gap-2 bg-orange-500 text-white px-4 py-2 rounded-xl"><Save size={18}/>{saving?'Đang lưu...':'Lưu thay đổi'}</button>:<button onClick={()=>setEditing(true)} className="flex gap-2 bg-orange-500 text-white px-4 py-2 rounded-xl"><Pencil size={18}/>Chỉnh sửa</button>}</div>
    <div className="bg-white rounded-2xl border p-6"><div className="flex gap-5">{editing?<label className="w-24 h-24 rounded-2xl overflow-hidden bg-orange-500 flex items-center justify-center text-white text-3xl cursor-pointer">{shop.logoUrl?<img src={shop.logoUrl} className="w-full h-full object-cover"/>:<Store/>}<input type="file" accept="image/*" className="hidden" onChange={e=>{const f=e.target.files?.[0];if(f){const rd=new FileReader();rd.onload=()=>change('logoUrl',rd.result as string);rd.readAsDataURL(f)}}}/></label>:<div className="w-24 h-24 rounded-2xl overflow-hidden bg-orange-500 flex items-center justify-center text-white text-3xl">{shop.logoUrl?<img src={shop.logoUrl} className="w-full h-full object-cover"/>:<Store/>}</div>}<div className="flex-1">{editing?<><input value={shop.name} onChange={e=>change('name',e.target.value)} className="text-xl font-bold w-full border rounded p-2"/><textarea value={shop.description} onChange={e=>change('description',e.target.value)} className="w-full mt-2 border rounded p-2" placeholder="Mô tả shop"/></>:<><h2 className="text-xl font-bold">{shop.name}</h2><p className="text-gray-500 mt-2">{shop.description}</p></>}<div className="flex gap-1 mt-3">{[1,2,3,4,5].map(i=><Star key={i} size={19} fill={i<=Math.round(rating)?'#f59e0b':'none'} color={i<=Math.round(rating)?'#f59e0b':'#d1d5db'}/>)}</div><span className="text-sm text-gray-600">{rating.toFixed(1)} / 5.0 ({shop.ratingCount||0} đánh giá)</span></div></div></div>
    <div className="grid grid-cols-3 gap-4">{[['Đánh giá trung bình',rating.toFixed(1),Star],['Tổng đơn hàng',shop.totalOrders||0,ShoppingCart],['Tỷ lệ hoàn thành',`${shop.completionRate||0}%`,Package]].map(([l,v,I]:any)=><div key={l} className="bg-white border rounded-2xl p-4 text-center"><I className="mx-auto text-orange-500"/><b className="block text-xl mt-2">{v}</b><span className="text-sm text-gray-500">{l}</span></div>)}</div>
    <div className="bg-white border rounded-2xl p-6"><h3 className="font-bold mb-4">Thông tin liên hệ</h3>{fields.map(([key,label,Icon]:any)=><div key={key} className="flex gap-3 items-center mb-3"><Icon className="text-orange-500"/><span className="w-28 text-sm">{label}</span>{editing?<input value={shop[key]||''} onChange={e=>change(key,e.target.value)} className="border rounded px-3 py-2 flex-1"/>:<span className="flex-1">{shop[key]||'Chưa cập nhật'}</span>}</div>)}</div></div>;
}
