namespace WEDBANDOAN.Models;
public sealed class SellerDashboardViewModel { public decimal RevenueToday { get; init; } public int OrdersToday { get; init; } public int PendingOrders { get; init; } public int ShippingOrders { get; init; } public int CompletedOrders { get; init; } public int ReturnedOrders { get; init; } public int CancelledOrders { get; init; } public List<SellerRevenuePoint> RevenueByHour { get; init; } = []; public List<SellerRevenuePoint> OrdersByHour { get; init; } = []; public List<SellerTopProduct> TopProducts { get; init; } = []; public List<SellerRecentOrder> RecentOrders { get; init; } = []; }
public sealed class SellerRevenuePoint { public string Time { get; init; } = "00:00"; public decimal Revenue { get; init; } }
public sealed class SellerTopProduct { public string Name { get; init; } = ""; public int Quantity { get; init; } }
public sealed class SellerRecentOrder { public string OrderCode { get; init; } = ""; public string CustomerName { get; init; } = ""; public int ItemCount { get; init; } public decimal Total { get; init; } public string Status { get; init; } = ""; public DateTime OrderedAt { get; init; } }
public sealed class SellerOrderListItem { public string Id { get; init; } = ""; public string OrderCode { get; init; } = ""; public string Status { get; init; } = ""; public string PaymentMethod { get; init; } = ""; public string CustomerName { get; init; } = ""; public string CustomerPhone { get; init; } = ""; public string DeliveryAddress { get; init; } = ""; public string Note { get; init; } = ""; public string? ShipperName { get; init; } public decimal Total { get; init; } public DateTime OrderedAt { get; init; } public List<SellerOrderLineItem> Items { get; init; } = []; }
public sealed class SellerOrderLineItem { public string Id { get; init; } = ""; public string ProductName { get; init; } = ""; public decimal Price { get; init; } public int Quantity { get; init; } }
public sealed class SellerProductItem { public int Id { get; init; } public string Name { get; init; } = ""; public decimal Price { get; init; } public string Category { get; init; } = "Khác"; public string Status { get; init; } = "active"; public string Type { get; init; } = "single"; public string? Image { get; init; } public string Description { get; init; } = ""; }
public sealed class CreateSellerProductRequest { public string Name { get; init; } = ""; public decimal Price { get; init; } public string Category { get; init; } = "Khác"; public string? Description { get; init; } public string? Image { get; init; } public string Status { get; init; } = "active"; public string Type { get; init; } = "single"; }
