import { Order, Chat } from "./types";

export const mockOrders: Order[] = [
  {
    id: "1",
    code: "SN20260713001",
    senderName: "Cơm Tấm Sài Gòn",
    senderPhone: "0912345678",
    senderAddress: "12 Nguyễn Trãi, Quận 1, TP.HCM",
    shopName: "Cơm Tấm Sài Gòn",
    receiverName: "Trần Thị Mai",
    receiverPhone: "0987654321",
    receiverAddress: "45 Lê Lợi, Quận 3, TP.HCM",
    items: "Cơm sườn bì chả x2, canh rong biển x1",
    weight: 1.0,
    cod: 105000,
    shippingFee: 25000,
    distance: "3.2 km",
    status: "pending",
    createdAt: "2026-07-13T08:30:00",
    note: "Giao nóng, xin thêm 2 bịch nước mắm",
  },
  {
    id: "2",
    code: "SN20260713002",
    senderName: "Bánh Mì Sài Gòn",
    senderPhone: "0923456789",
    senderAddress: "88 Đinh Tiên Hoàng, Quận Bình Thạnh, TP.HCM",
    shopName: "Bánh Mì Sài Gòn",
    receiverName: "Lê Văn Hùng",
    receiverPhone: "0976543210",
    receiverAddress: "23 Phan Xích Long, Quận Phú Nhuận, TP.HCM",
    items: "Bánh mì thập cẩm x3",
    weight: 0.5,
    cod: 75000,
    shippingFee: 20000,
    distance: "1.8 km",
    status: "pending",
    createdAt: "2026-07-13T09:00:00",
  },
  {
    id: "3",
    code: "SN20260713003",
    senderName: "Bếp Nhà Mây",
    senderPhone: "0934567890",
    senderAddress: "156 Quang Trung, Quận Gò Vấp, TP.HCM",
    shopName: "Bếp Nhà Mây",
    receiverName: "Phạm Thị Lan",
    receiverPhone: "0965432109",
    receiverAddress: "78 Hoàng Văn Thụ, Quận Tân Bình, TP.HCM",
    items: "Lẩu Thái hải sản 2 người, trà tắc x2",
    weight: 2.5,
    cod: 239000,
    shippingFee: 30000,
    distance: "5.1 km",
    status: "pending",
    createdAt: "2026-07-13T07:45:00",
    note: "Giữ nồi lẩu thẳng, giao kèm rau và nước chấm",
  },
  {
    id: "4",
    code: "SN20260713004",
    senderName: "Gà Rán Giòn Cay",
    senderPhone: "0945678901",
    senderAddress: "34 Cách Mạng Tháng 8, Quận 10, TP.HCM",
    shopName: "Gà Rán Giòn Cay",
    receiverName: "Nguyễn Thị Hoa",
    receiverPhone: "0954321098",
    receiverAddress: "19 Nguyễn Thị Minh Khai, Quận 1, TP.HCM",
    items: "Gà rán 6 miếng, khoai tây, Pepsi x2",
    weight: 1.4,
    cod: 189000,
    shippingFee: 22000,
    distance: "2.4 km",
    status: "pending",
    createdAt: "2026-07-13T06:30:00",
  },
  {
    id: "5",
    code: "SN20260713005",
    senderName: "Bún Bò Huế Cô Ba",
    senderPhone: "0905888777",
    senderAddress: "102 Võ Văn Tần, Quận 3, TP.HCM",
    shopName: "Bún Bò Huế Cô Ba",
    receiverName: "Đặng Minh Khoa",
    receiverPhone: "0938111222",
    receiverAddress: "61 Nguyễn Đình Chiểu, Quận 1, TP.HCM",
    items: "Bún bò đặc biệt x2, chả cua thêm x1",
    weight: 1.6,
    cod: 145000,
    shippingFee: 18000,
    distance: "2.1 km",
    status: "pending",
    createdAt: "2026-07-13T09:20:00",
    note: "Một phần không hành, để nước dùng riêng",
  },
  {
    id: "6",
    code: "SN20260713006",
    senderName: "Trà Sữa Nhà Lá",
    senderPhone: "0977444555",
    senderAddress: "25 Hoa Sứ, Quận Phú Nhuận, TP.HCM",
    shopName: "Trà Sữa Nhà Lá",
    receiverName: "Nguyễn Khánh Vy",
    receiverPhone: "0962333444",
    receiverAddress: "90 Phan Đăng Lưu, Quận Bình Thạnh, TP.HCM",
    items: "Trà sữa trân châu x2, matcha đá xay x1",
    weight: 1.3,
    cod: 126000,
    shippingFee: 22000,
    distance: "3.6 km",
    status: "pending",
    createdAt: "2026-07-13T09:35:00",
    note: "Giữ ly đứng, không để đổ đá",
  },
];

export const mockHistory: Order[] = [
  {
    id: "h1",
    code: "SN20260712001",
    senderName: "Cà Phê Trung Nguyên",
    senderPhone: "0901111111",
    senderAddress: "5 Đinh Lễ, Hoàn Kiếm, Hà Nội",
    shopName: "Cà Phê Trung Nguyên",
    receiverName: "Đỗ Minh Tuấn",
    receiverPhone: "0902222222",
    receiverAddress: "12 Tràng Thi, Hoàn Kiếm, Hà Nội",
    items: "Cà phê sữa đá x2, bánh mì que x2",
    weight: 0.8,
    cod: 120000,
    shippingFee: 18000,
    distance: "1.2 km",
    status: "delivered",
    createdAt: "2026-07-12T14:00:00",
    customerRating: 5,
    shopRating: 5,
    ratingMessage: "Khách nhận món nhanh, quán chuẩn bị đúng giờ và đóng gói cẩn thận.",
    customerRatingMessage: "Khách nhận món nhanh và liên lạc dễ dàng.",
    shopRatingMessage: "Quán chuẩn bị đúng giờ, đóng gói cẩn thận.",
    ratingSubmittedAt: new Date(Date.now() - 20 * 60 * 1000).toISOString(),
  },
  {
    id: "h2",
    code: "SN20260712002",
    senderName: "Pizza Lò Gạch",
    senderPhone: "0903333333",
    senderAddress: "67 Bà Triệu, Hai Bà Trưng, Hà Nội",
    shopName: "Pizza Lò Gạch",
    receiverName: "Hoàng Thị Yến",
    receiverPhone: "0904444444",
    receiverAddress: "45 Lò Đúc, Hai Bà Trưng, Hà Nội",
    items: "Pizza hải sản size L, mì Ý bò bằm",
    weight: 1.8,
    cod: 298000,
    shippingFee: 30000,
    distance: "2.5 km",
    status: "delivered",
    createdAt: "2026-07-12T11:30:00",
    customerRating: 4,
    shopRating: 5,
    ratingMessage: "Khách dễ liên lạc, quán bàn giao món đầy đủ.",
    customerRatingMessage: "Khách dễ liên lạc và chỉ đường rõ ràng.",
    shopRatingMessage: "Quán bàn giao món đầy đủ, đúng đơn.",
  },
  {
    id: "h3",
    code: "SN20260712003",
    senderName: "Chè Ngon 365",
    senderPhone: "0905555555",
    senderAddress: "23 Nguyễn Du, Hai Bà Trưng, Hà Nội",
    shopName: "Chè Ngon 365",
    receiverName: "Vũ Thanh Long",
    receiverPhone: "0906666666",
    receiverAddress: "89 Trần Nhân Tông, Hai Bà Trưng, Hà Nội",
    items: "Chè khúc bạch x2, chè thái sầu riêng x1",
    weight: 0.5,
    cod: 0,
    shippingFee: 25000,
    distance: "1.8 km",
    status: "delivered",
    createdAt: "2026-07-12T09:00:00",
    note: "Đã giao đủ món, khách thanh toán thành công",
    customerRating: 4,
    shopRating: 4,
    ratingMessage: "Giao nhận thuận lợi, hai bên phối hợp tốt.",
    customerRatingMessage: "Khách phối hợp nhận món tốt.",
    shopRatingMessage: "Quán hỗ trợ shipper nhanh chóng.",
  },
  {
    id: "h4",
    code: "SN20260711001",
    senderName: "Bánh Cuốn Nóng Hà Nội",
    senderPhone: "0907777777",
    senderAddress: "15 Đinh Tiên Hoàng, Hoàn Kiếm, Hà Nội",
    shopName: "Bánh Cuốn Nóng Hà Nội",
    receiverName: "Nguyễn Văn Bình",
    receiverPhone: "0908888888",
    receiverAddress: "33 Hàng Bài, Hoàn Kiếm, Hà Nội",
    items: "Bánh cuốn chả quế x3, sữa đậu nành x2",
    weight: 1.7,
    cod: 135000,
    shippingFee: 20000,
    distance: "0.9 km",
    status: "delivered",
    createdAt: "2026-07-11T16:00:00",
    customerRating: 5,
    shopRating: 4,
    ratingMessage: "Khách thân thiện, quán chuẩn bị món hơi chậm nhưng đóng gói tốt.",
    customerRatingMessage: "Khách thân thiện và nhận món đúng giờ.",
    shopRatingMessage: "Quán chuẩn bị hơi chậm nhưng đóng gói tốt.",
  },
];

export const mockChats: Chat[] = [
  {
    id: "c1",
    orderId: "1",
    orderCode: "SN20260713001",
    with: "Trần Thị Mai",
    type: "customer",
    avatar: "TM",
    lastMessage: "Bạn giao đến thì gọi mình xuống nhận nhé",
    lastTime: "08:42",
    unread: 1,
    messages: [
      { id: "m1", from: "shipper", text: "Mình đã nhận đơn cơm tấm và đang đến quán lấy món ạ.", time: "08:40" },
      { id: "m2", from: "other", text: "Bạn giao đến thì gọi mình xuống nhận nhé", time: "08:42" },
    ],
  },
  {
    id: "c2",
    orderId: "1",
    orderCode: "SN20260713001",
    with: "Cơm Tấm Sài Gòn",
    type: "seller",
    avatar: "CT",
    lastMessage: "Đơn cơm sườn bì chả đang được đóng gói",
    lastTime: "08:38",
    unread: 0,
    messages: [
      { id: "m3", from: "shipper", text: "Mình đang tới quán lấy đơn #SN20260713001 ạ.", time: "08:35" },
      { id: "m4", from: "other", text: "Đơn cơm sườn bì chả đang được đóng gói, khoảng 5 phút nữa xong nhé.", time: "08:38" },
    ],
  },
];
